version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-node
      - image: circleci/postgres:9.5-postgis-ram
    steps:
      - checkout
      - run: echo "A first hello"
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: bundle install & bundle clean
      - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns
          - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - v1-gem-cache-{{ arch }}-{{ .Branch }}-
          - v1-gem-cache-{{ arch }}-
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      #- run: bin/setup
      - run: rake
              
  two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "a more familiar hello"

workflows:
  version: 2
  toptutoring-workflows:
    jobs:
      - build

